[workspace]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
name = "max_offline"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
mojo = "==1.0.0b2.dev2026052006"
modular = ">=26.4.0.dev2026052006,<27"
